### ISSUE TITLE
ADAPT Icon Missing

### ISSUE THREAD

**Issue by ethanaturner** [LibreTexts/ckeditor-query-plugin#45]
Hi all,

It looks like the ADAPT icon has gone missing again (returns 404). Any way we can get this back soon? We have a number of training workshops over the next few weeks. 

If you'd like, I can upload the icon to our native CDN and get you a permalink! 😃 

https://github.com/LibreTexts/ckeditor-query-plugin/blob/865eb040932fd101f1990946657515621de7758c/src/scripts/plugin.js#L126

**Comment by TimStewartJ** [comment]
Thanks for reporting this. A permalink would be perfect, feel free to post back with that and I'll update the plugin with it. You could even submit a PR with an updated link if you wanted, whatever works best for you!
